main: biz.yama2211.opengui.Main
name: ${project.artifactId}
version: ${project.version}
author: yamagami2211
website: https://forum.civa.jp/viewtopic.php?f=15&t=368#p1251

commands:
  enderchest:
    description: enderchest
  inventory:
    description: inventory
  workbench:
    description: workbench
  enchanting:
    description: enchanting
  opengui:
    description: opengui
  opengui.reload:
    description: opengui

permissions:
  opengui.enderchest:
    description: インベントリを開く
    default: op
  opengui.enderchest.other:
    description: 他プレイヤーのインベントリを開く
    default: op
  opengui.inventory:
    description: エンダーチェストを開く
    default: op
  opengui.inventory.other:
    description: 他プレイヤーのエンダーチェストを開く
    default: op
  opengui.workbench:
    description: ワークベンチを開く
    default: op
  opengui.enchanting:
    description: エンチャントテーブルを開く
    default: op
  opengui.reload:
    description: Configをリロード
    default: op
    
  opengui.*:
    description: 全コマンドの権限
    default: op
    children:
      opengui.enderchest: true
      opengui.enderchest.other: true
      opengui.inventory: true
      opengui.inventory.other: true
      opengui.workbench: true
      opengui.enchanting: true
      opengui.reload: true

  opengui.other.*:
    description: 他プレイヤーを開く系コマンドの権限
    default: op
    children:
      opengui.enderchest.other: true
      opengui.inventory.other: true
